trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

parameters:
- name: vercelProject
  type: string
  displayName: 'The name of your Vercel Project'
- name: vercelToken
  type: string
  displayName: 'A Vercel personal access token with deploy permissions for your Vercel Project (https://vercel.com/guides/how-do-i-use-a-vercel-api-access-token)'
- name: production
  type: string
  default: $(isMain)
  displayName: 'Should the task deploy to production? Defaults to true for Main branch, false otherwise.'
- name: azureToken
  type: string
  displayName: 'An Azure personal access token with the Git 'PullRequestContribute' permission for your Azure DevOps Organization (https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate)'

steps:
- task: vercel-deployment-task@0
  inputs:
    vercelProject: ${{ parameters.vercelToken }}
    vercelToken: ${{ parameters.vercelToken }}
    production: 
    azureToken: ${{ parameters.azureToken }}
  condition: or(eq(variables.isMain, true), eq(variables['Build.Reason'], 'PullRequest'))